### PR TITLE
lint: re-enable and fix linting

### PR DESCRIPTION
**Pull request by Catalyst4222**

### CODE REVIEW

**Comment by Ascellayn** [comment]
dm me on discord ```@siriusbyt``` to explain to me what you modified exactly, I was supposed to go back to it and fix it myself while trying to learn more typescript but didn't get the time so far.
TLDR: please give me a crash course on what you modified and how I can improve my shitty code
i'll accept PR when i'll 100% understand the new code

**Comment by Ascellayn** [comment]
also now that i think about it, should have asked the same thing with @tharki-god, oops.

**Comment by yofukashino** [comment]
kekw

**Comment by yofukashino** [comment]
my implementation was even better

**Comment by Ascellayn** [comment]
> my implementation was even better

fight to the death
make counter pr or whatever the hell it's called lol

**Comment by yofukashino** [comment]
done

**Comment by Ascellayn** [comment]
> done

lmfao ok now explain your code cause i don't understand shit
at least this pr right here i can somewhat understand it xdddddd

**Comment by yofukashino** [comment]
come dc call I will

**Comment by Ascellayn** [comment]
> come dc call I will

i'm litterally going to school right now im dying of cringe

**Comment by yofukashino** [comment]
> > come dc call I will
> 
> i'm litterally going to school right now im dying of cringe

lmfao dead anyways later then

**Pull request merged**
